{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.56",
   "distribution_type" : "module",
   "version" : "1.56",
   "name" : "Gtk2-CV",
   "author" : [],
   "license" : "unknown",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "Guard" : 1.02,
      "IO::AIO" : 3.2,
      "Gtk2::Ex::PodViewer" : 0.17,
      "Glib" : 1.08,
      "Gtk2" : 1.08,
      "common::sense" : 2.03,
      "Gtk2::GladeXML" : 0.93
   },
   "abstract" : null,
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
