--- #YAML:1.0
name:               Gtk2-CV
version:            1.54
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib:                 1.08
    Gtk2:                 1.08
    Gtk2::Ex::PodViewer:  0.17
    Gtk2::GladeXML:       0.93
    IO::AIO:              2.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
