--- #YAML:1.0
name:                Gtk2-CV
version:             1.53
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Glib:                          1.08
    Gtk2:                          1.08
    Gtk2::Ex::PodViewer:           0.17
    Gtk2::GladeXML:                0.93
    IO::AIO:                       2.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
